name: ditonton_submission1
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  about:
    path: about
  bloc: ^9.0.0
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  cached_network_image: ^3.4.1
  core:
    path: core

  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  data_connection_checker:
    git:
      url: https://github.com/chornthorn/data_connection_checker.git
      ref: master
  equatable: ^2.0.7
  firebase_analytics: ^11.4.6
  firebase_core: ^3.13.1
  firebase_crashlytics: ^4.3.6
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_lints: ^5.0.0
  flutter_rating_bar: ^4.0.1
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  home:
    path: home
  http: ^1.4.0
  mockito: ^5.4.6
  path: ^1.8.3
  path_provider: ^2.1.5
  provider: ^6.1.4
  rxdart: ^0.28.0
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite_common_ffi: ^2.3.5

flutter:
  uses-material-design: true

  assets:
    - assets/
    - certificates/
