publish_to: none

name: home
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  core:
    path: ../core

  about:
    path: ../about

  dartz: ^0.10.1
  mockito: ^5.4.6
  build_runner: ^2.4.15
  provider: ^6.1.5
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  network_image_mock: ^2.1.0
  flutter_bloc: ^9.1.1
  bloc_test: ^10.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/
