// Mocks generated by Mockito 5.4.6 from annotations
// in ditonton_submission1/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i25;
import 'dart:convert' as _i41;
import 'dart:typed_data' as _i42;
import 'dart:ui' as _i26;

import 'package:core/core.dart' as _i23;
import 'package:dartz/dartz.dart' as _i3;
import 'package:data_connection_checker/data_connection_checker.dart' as _i20;
import 'package:ditonton_submission1/data/datasources/db/movie_database_helper.dart'
    as _i29;
import 'package:ditonton_submission1/data/datasources/db/tv_database_helper.dart'
    as _i31;
import 'package:ditonton_submission1/data/datasources/movie_local_data_source.dart'
    as _i43;
import 'package:ditonton_submission1/data/datasources/movie_remote_data_source.dart'
    as _i27;
import 'package:ditonton_submission1/data/datasources/tv_local_data_source.dart'
    as _i44;
import 'package:ditonton_submission1/data/datasources/tv_remote_data_source.dart'
    as _i28;
import 'package:ditonton_submission1/data/models/movie_detail_model.dart'
    as _i4;
import 'package:ditonton_submission1/data/models/tv_detail_model.dart' as _i5;
import 'package:ditonton_submission1/domain/usecases/movie/get_movie_detail.dart'
    as _i11;
import 'package:ditonton_submission1/domain/usecases/movie/get_movie_recommendations.dart'
    as _i12;
import 'package:ditonton_submission1/domain/usecases/movie/get_watchlist_movies.dart'
    as _i18;
import 'package:ditonton_submission1/domain/usecases/movie/get_watchlist_status_movie.dart'
    as _i13;
import 'package:ditonton_submission1/domain/usecases/movie/remove_watchlist_movie.dart'
    as _i15;
import 'package:ditonton_submission1/domain/usecases/movie/save_watchlist_movie.dart'
    as _i14;
import 'package:ditonton_submission1/domain/usecases/movie/search_movies.dart'
    as _i17;
import 'package:ditonton_submission1/domain/usecases/tv/get_tv_detail.dart'
    as _i6;
import 'package:ditonton_submission1/domain/usecases/tv/get_tv_recommendations.dart'
    as _i7;
import 'package:ditonton_submission1/domain/usecases/tv/get_watchlist_status_tv.dart'
    as _i8;
import 'package:ditonton_submission1/domain/usecases/tv/get_watchlist_tv.dart'
    as _i19;
import 'package:ditonton_submission1/domain/usecases/tv/remove_watchlist_tv.dart'
    as _i10;
import 'package:ditonton_submission1/domain/usecases/tv/save_watchlist_tv.dart'
    as _i9;
import 'package:ditonton_submission1/domain/usecases/tv/search_tv.dart' as _i16;
import 'package:ditonton_submission1/presentation/provider/movies/movie_detail_notifier.dart'
    as _i35;
import 'package:ditonton_submission1/presentation/provider/movies/movie_search_notifier.dart'
    as _i38;
import 'package:ditonton_submission1/presentation/provider/movies/top_rated_movies_notifier.dart'
    as _i22;
import 'package:ditonton_submission1/presentation/provider/movies/watchlist_movie_notifier.dart'
    as _i39;
import 'package:ditonton_submission1/presentation/provider/tv/popular_tv_notifier.dart'
    as _i36;
import 'package:ditonton_submission1/presentation/provider/tv/top_rated_tv_notifier.dart'
    as _i32;
import 'package:ditonton_submission1/presentation/provider/tv/tv_detail_notifier.dart'
    as _i33;
import 'package:ditonton_submission1/presentation/provider/tv/tv_search_notifier.dart'
    as _i37;
import 'package:ditonton_submission1/presentation/provider/tv/watchlist_tv_notifier.dart'
    as _i40;
import 'package:home/home.dart' as _i2;
import 'package:home/presentation/provider/popular_movies_notifier.dart'
    as _i34;
import 'package:http/http.dart' as _i21;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i24;
import 'package:sqflite/sqflite.dart' as _i30;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetTopRatedMovies_0 extends _i1.SmartFake
    implements _i2.GetTopRatedMovies {
  _FakeGetTopRatedMovies_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieRepository_1 extends _i1.SmartFake
    implements _i2.MovieRepository {
  _FakeMovieRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTvRepository_3 extends _i1.SmartFake implements _i2.TvRepository {
  _FakeTvRepository_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieDetailResponse_4 extends _i1.SmartFake
    implements _i4.MovieDetailResponse {
  _FakeMovieDetailResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTvDetailResponse_5 extends _i1.SmartFake
    implements _i5.TvDetailResponse {
  _FakeTvDetailResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTopRatedTv_6 extends _i1.SmartFake implements _i2.GetTopRatedTv {
  _FakeGetTopRatedTv_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTvDetail_7 extends _i1.SmartFake implements _i6.GetTvDetail {
  _FakeGetTvDetail_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTvRecommendations_8 extends _i1.SmartFake
    implements _i7.GetTvRecommendations {
  _FakeGetTvRecommendations_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetWatchListStatusTv_9 extends _i1.SmartFake
    implements _i8.GetWatchListStatusTv {
  _FakeGetWatchListStatusTv_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSaveWatchlistTv_10 extends _i1.SmartFake
    implements _i9.SaveWatchlistTv {
  _FakeSaveWatchlistTv_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRemoveWatchlistTv_11 extends _i1.SmartFake
    implements _i10.RemoveWatchlistTv {
  _FakeRemoveWatchlistTv_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetPopularMovies_12 extends _i1.SmartFake
    implements _i2.GetPopularMovies {
  _FakeGetPopularMovies_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetMovieDetail_13 extends _i1.SmartFake
    implements _i11.GetMovieDetail {
  _FakeGetMovieDetail_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetMovieRecommendations_14 extends _i1.SmartFake
    implements _i12.GetMovieRecommendations {
  _FakeGetMovieRecommendations_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetWatchListStatusMovie_15 extends _i1.SmartFake
    implements _i13.GetWatchListStatusMovie {
  _FakeGetWatchListStatusMovie_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSaveWatchlistMovie_16 extends _i1.SmartFake
    implements _i14.SaveWatchlistMovie {
  _FakeSaveWatchlistMovie_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRemoveWatchlistMovie_17 extends _i1.SmartFake
    implements _i15.RemoveWatchlistMovie {
  _FakeRemoveWatchlistMovie_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieDetail_18 extends _i1.SmartFake implements _i2.MovieDetail {
  _FakeMovieDetail_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetPopularTv_19 extends _i1.SmartFake implements _i2.GetPopularTv {
  _FakeGetPopularTv_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchTv_20 extends _i1.SmartFake implements _i16.SearchTv {
  _FakeSearchTv_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchMovies_21 extends _i1.SmartFake implements _i17.SearchMovies {
  _FakeSearchMovies_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetWatchlistMovies_22 extends _i1.SmartFake
    implements _i18.GetWatchlistMovies {
  _FakeGetWatchlistMovies_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetWatchListTv_23 extends _i1.SmartFake
    implements _i19.GetWatchListTv {
  _FakeGetWatchListTv_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_24 extends _i1.SmartFake implements Duration {
  _FakeDuration_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAddressCheckResult_25 extends _i1.SmartFake
    implements _i20.AddressCheckResult {
  _FakeAddressCheckResult_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_26 extends _i1.SmartFake implements _i21.Response {
  _FakeResponse_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamedResponse_27 extends _i1.SmartFake
    implements _i21.StreamedResponse {
  _FakeStreamedResponse_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TopRatedMoviesNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopRatedMoviesNotifier extends _i1.Mock
    implements _i22.TopRatedMoviesNotifier {
  MockTopRatedMoviesNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTopRatedMovies get getTopRatedMovies =>
      (super.noSuchMethod(
            Invocation.getter(#getTopRatedMovies),
            returnValue: _FakeGetTopRatedMovies_0(
              this,
              Invocation.getter(#getTopRatedMovies),
            ),
          )
          as _i2.GetTopRatedMovies);

  @override
  _i23.RequestState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i23.RequestState.empty,
          )
          as _i23.RequestState);

  @override
  List<_i2.Movie> get movies =>
      (super.noSuchMethod(
            Invocation.getter(#movies),
            returnValue: <_i2.Movie>[],
          )
          as List<_i2.Movie>);

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i24.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i25.Future<void> fetchTopRatedMovies() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTopRatedMovies, []),
            returnValue: _i25.Future<void>.value(),
            returnValueForMissingStub: _i25.Future<void>.value(),
          )
          as _i25.Future<void>);

  @override
  void addListener(_i26.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i26.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GetTopRatedMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTopRatedMovies extends _i1.Mock implements _i2.GetTopRatedMovies {
  MockGetTopRatedMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.MovieRepository);

  @override
  _i25.Future<_i3.Either<_i23.Failure, List<_i2.Movie>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i25.Future<_i3.Either<_i23.Failure, List<_i2.Movie>>>.value(
                  _FakeEither_2<_i23.Failure, List<_i2.Movie>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, List<_i2.Movie>>>);
}

/// A class which mocks [GetTopRatedTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTopRatedTv extends _i1.Mock implements _i2.GetTopRatedTv {
  MockGetTopRatedTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.TvRepository);

  @override
  _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>>.value(
                  _FakeEither_2<_i23.Failure, List<_i2.Tv>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>>);
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i2.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i25.Future<_i3.Either<_i23.Failure, List<_i2.Movie>>>
  getNowPlayingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlayingMovies, []),
            returnValue:
                _i25.Future<_i3.Either<_i23.Failure, List<_i2.Movie>>>.value(
                  _FakeEither_2<_i23.Failure, List<_i2.Movie>>(
                    this,
                    Invocation.method(#getNowPlayingMovies, []),
                  ),
                ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, List<_i2.Movie>>>);

  @override
  _i25.Future<_i3.Either<_i23.Failure, List<_i2.Movie>>> getPopularMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularMovies, []),
            returnValue:
                _i25.Future<_i3.Either<_i23.Failure, List<_i2.Movie>>>.value(
                  _FakeEither_2<_i23.Failure, List<_i2.Movie>>(
                    this,
                    Invocation.method(#getPopularMovies, []),
                  ),
                ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, List<_i2.Movie>>>);

  @override
  _i25.Future<_i3.Either<_i23.Failure, List<_i2.Movie>>> getTopRatedMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedMovies, []),
            returnValue:
                _i25.Future<_i3.Either<_i23.Failure, List<_i2.Movie>>>.value(
                  _FakeEither_2<_i23.Failure, List<_i2.Movie>>(
                    this,
                    Invocation.method(#getTopRatedMovies, []),
                  ),
                ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, List<_i2.Movie>>>);

  @override
  _i25.Future<_i3.Either<_i23.Failure, _i2.MovieDetail>> getMovieDetail(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieDetail, [id]),
            returnValue:
                _i25.Future<_i3.Either<_i23.Failure, _i2.MovieDetail>>.value(
                  _FakeEither_2<_i23.Failure, _i2.MovieDetail>(
                    this,
                    Invocation.method(#getMovieDetail, [id]),
                  ),
                ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, _i2.MovieDetail>>);

  @override
  _i25.Future<_i3.Either<_i23.Failure, List<_i2.Movie>>>
  getMovieRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieRecommendations, [id]),
            returnValue:
                _i25.Future<_i3.Either<_i23.Failure, List<_i2.Movie>>>.value(
                  _FakeEither_2<_i23.Failure, List<_i2.Movie>>(
                    this,
                    Invocation.method(#getMovieRecommendations, [id]),
                  ),
                ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, List<_i2.Movie>>>);

  @override
  _i25.Future<_i3.Either<_i23.Failure, List<_i2.Movie>>> searchMovies(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchMovies, [query]),
            returnValue:
                _i25.Future<_i3.Either<_i23.Failure, List<_i2.Movie>>>.value(
                  _FakeEither_2<_i23.Failure, List<_i2.Movie>>(
                    this,
                    Invocation.method(#searchMovies, [query]),
                  ),
                ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, List<_i2.Movie>>>);

  @override
  _i25.Future<_i3.Either<_i23.Failure, String>> saveWatchlist(
    _i2.MovieDetail? movie,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveWatchlist, [movie]),
            returnValue: _i25.Future<_i3.Either<_i23.Failure, String>>.value(
              _FakeEither_2<_i23.Failure, String>(
                this,
                Invocation.method(#saveWatchlist, [movie]),
              ),
            ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, String>>);

  @override
  _i25.Future<_i3.Either<_i23.Failure, String>> removeWatchlist(
    _i2.MovieDetail? movie,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [movie]),
            returnValue: _i25.Future<_i3.Either<_i23.Failure, String>>.value(
              _FakeEither_2<_i23.Failure, String>(
                this,
                Invocation.method(#removeWatchlist, [movie]),
              ),
            ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, String>>);

  @override
  _i25.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isAddedToWatchlist, [id]),
            returnValue: _i25.Future<bool>.value(false),
          )
          as _i25.Future<bool>);

  @override
  _i25.Future<_i3.Either<_i23.Failure, List<_i2.Movie>>> getWatchlistMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistMovies, []),
            returnValue:
                _i25.Future<_i3.Either<_i23.Failure, List<_i2.Movie>>>.value(
                  _FakeEither_2<_i23.Failure, List<_i2.Movie>>(
                    this,
                    Invocation.method(#getWatchlistMovies, []),
                  ),
                ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, List<_i2.Movie>>>);
}

/// A class which mocks [TvRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRepository extends _i1.Mock implements _i2.TvRepository {
  MockTvRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>> getOnTheAirTv() =>
      (super.noSuchMethod(
            Invocation.method(#getOnTheAirTv, []),
            returnValue:
                _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>>.value(
                  _FakeEither_2<_i23.Failure, List<_i2.Tv>>(
                    this,
                    Invocation.method(#getOnTheAirTv, []),
                  ),
                ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>>);

  @override
  _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>> getPopularTv() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTv, []),
            returnValue:
                _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>>.value(
                  _FakeEither_2<_i23.Failure, List<_i2.Tv>>(
                    this,
                    Invocation.method(#getPopularTv, []),
                  ),
                ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>>);

  @override
  _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>> getTopRatedTv() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedTv, []),
            returnValue:
                _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>>.value(
                  _FakeEither_2<_i23.Failure, List<_i2.Tv>>(
                    this,
                    Invocation.method(#getTopRatedTv, []),
                  ),
                ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>>);

  @override
  _i25.Future<_i3.Either<_i23.Failure, _i2.TvDetail>> getTvDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvDetail, [id]),
            returnValue:
                _i25.Future<_i3.Either<_i23.Failure, _i2.TvDetail>>.value(
                  _FakeEither_2<_i23.Failure, _i2.TvDetail>(
                    this,
                    Invocation.method(#getTvDetail, [id]),
                  ),
                ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, _i2.TvDetail>>);

  @override
  _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>> getTvRecommendations(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTvRecommendations, [id]),
            returnValue:
                _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>>.value(
                  _FakeEither_2<_i23.Failure, List<_i2.Tv>>(
                    this,
                    Invocation.method(#getTvRecommendations, [id]),
                  ),
                ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>>);

  @override
  _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>> searchTv(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTv, [query]),
            returnValue:
                _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>>.value(
                  _FakeEither_2<_i23.Failure, List<_i2.Tv>>(
                    this,
                    Invocation.method(#searchTv, [query]),
                  ),
                ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>>);

  @override
  _i25.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isAddedToWatchlist, [id]),
            returnValue: _i25.Future<bool>.value(false),
          )
          as _i25.Future<bool>);

  @override
  _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>> getWatchlistTv() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistTv, []),
            returnValue:
                _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>>.value(
                  _FakeEither_2<_i23.Failure, List<_i2.Tv>>(
                    this,
                    Invocation.method(#getWatchlistTv, []),
                  ),
                ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>>);

  @override
  _i25.Future<_i3.Either<_i23.Failure, String>> saveWatchlist(
    _i2.TvDetail? tv,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveWatchlist, [tv]),
            returnValue: _i25.Future<_i3.Either<_i23.Failure, String>>.value(
              _FakeEither_2<_i23.Failure, String>(
                this,
                Invocation.method(#saveWatchlist, [tv]),
              ),
            ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, String>>);

  @override
  _i25.Future<_i3.Either<_i23.Failure, String>> removeWatchlist(
    _i2.TvDetail? tv,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [tv]),
            returnValue: _i25.Future<_i3.Either<_i23.Failure, String>>.value(
              _FakeEither_2<_i23.Failure, String>(
                this,
                Invocation.method(#removeWatchlist, [tv]),
              ),
            ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, String>>);
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i1.Mock
    implements _i27.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i25.Future<List<_i2.MovieModel>> getNowPlayingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlayingMovies, []),
            returnValue: _i25.Future<List<_i2.MovieModel>>.value(
              <_i2.MovieModel>[],
            ),
          )
          as _i25.Future<List<_i2.MovieModel>>);

  @override
  _i25.Future<List<_i2.MovieModel>> getPopularMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularMovies, []),
            returnValue: _i25.Future<List<_i2.MovieModel>>.value(
              <_i2.MovieModel>[],
            ),
          )
          as _i25.Future<List<_i2.MovieModel>>);

  @override
  _i25.Future<List<_i2.MovieModel>> getTopRatedMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedMovies, []),
            returnValue: _i25.Future<List<_i2.MovieModel>>.value(
              <_i2.MovieModel>[],
            ),
          )
          as _i25.Future<List<_i2.MovieModel>>);

  @override
  _i25.Future<_i4.MovieDetailResponse> getMovieDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieDetail, [id]),
            returnValue: _i25.Future<_i4.MovieDetailResponse>.value(
              _FakeMovieDetailResponse_4(
                this,
                Invocation.method(#getMovieDetail, [id]),
              ),
            ),
          )
          as _i25.Future<_i4.MovieDetailResponse>);

  @override
  _i25.Future<List<_i2.MovieModel>> getMovieRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieRecommendations, [id]),
            returnValue: _i25.Future<List<_i2.MovieModel>>.value(
              <_i2.MovieModel>[],
            ),
          )
          as _i25.Future<List<_i2.MovieModel>>);

  @override
  _i25.Future<List<_i2.MovieModel>> searchMovies(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchMovies, [query]),
            returnValue: _i25.Future<List<_i2.MovieModel>>.value(
              <_i2.MovieModel>[],
            ),
          )
          as _i25.Future<List<_i2.MovieModel>>);
}

/// A class which mocks [TvRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRemoteDataSource extends _i1.Mock
    implements _i28.TvRemoteDataSource {
  MockTvRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i25.Future<List<_i2.TvModel>> getOnTheAirTv() =>
      (super.noSuchMethod(
            Invocation.method(#getOnTheAirTv, []),
            returnValue: _i25.Future<List<_i2.TvModel>>.value(<_i2.TvModel>[]),
          )
          as _i25.Future<List<_i2.TvModel>>);

  @override
  _i25.Future<List<_i2.TvModel>> getPopularTv() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTv, []),
            returnValue: _i25.Future<List<_i2.TvModel>>.value(<_i2.TvModel>[]),
          )
          as _i25.Future<List<_i2.TvModel>>);

  @override
  _i25.Future<List<_i2.TvModel>> getTopRatedTv() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedTv, []),
            returnValue: _i25.Future<List<_i2.TvModel>>.value(<_i2.TvModel>[]),
          )
          as _i25.Future<List<_i2.TvModel>>);

  @override
  _i25.Future<_i5.TvDetailResponse> getTvDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvDetail, [id]),
            returnValue: _i25.Future<_i5.TvDetailResponse>.value(
              _FakeTvDetailResponse_5(
                this,
                Invocation.method(#getTvDetail, [id]),
              ),
            ),
          )
          as _i25.Future<_i5.TvDetailResponse>);

  @override
  _i25.Future<List<_i2.TvModel>> searchTv(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTv, [query]),
            returnValue: _i25.Future<List<_i2.TvModel>>.value(<_i2.TvModel>[]),
          )
          as _i25.Future<List<_i2.TvModel>>);

  @override
  _i25.Future<List<_i2.TvModel>> getTvRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvRecommendations, [id]),
            returnValue: _i25.Future<List<_i2.TvModel>>.value(<_i2.TvModel>[]),
          )
          as _i25.Future<List<_i2.TvModel>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i23.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i25.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i25.Future<bool>.value(false),
          )
          as _i25.Future<bool>);
}

/// A class which mocks [GetMovieDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMovieDetail extends _i1.Mock implements _i11.GetMovieDetail {
  MockGetMovieDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.MovieRepository);

  @override
  _i25.Future<_i3.Either<_i23.Failure, _i2.MovieDetail>> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue:
                _i25.Future<_i3.Either<_i23.Failure, _i2.MovieDetail>>.value(
                  _FakeEither_2<_i23.Failure, _i2.MovieDetail>(
                    this,
                    Invocation.method(#execute, [id]),
                  ),
                ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, _i2.MovieDetail>>);
}

/// A class which mocks [GetMovieRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMovieRecommendations extends _i1.Mock
    implements _i12.GetMovieRecommendations {
  MockGetMovieRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.MovieRepository);

  @override
  _i25.Future<_i3.Either<_i23.Failure, List<_i2.Movie>>> execute(dynamic id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue:
                _i25.Future<_i3.Either<_i23.Failure, List<_i2.Movie>>>.value(
                  _FakeEither_2<_i23.Failure, List<_i2.Movie>>(
                    this,
                    Invocation.method(#execute, [id]),
                  ),
                ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, List<_i2.Movie>>>);
}

/// A class which mocks [GetWatchListStatusMovie].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchListStatusMovie extends _i1.Mock
    implements _i13.GetWatchListStatusMovie {
  MockGetWatchListStatusMovie() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.MovieRepository);

  @override
  _i25.Future<bool> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue: _i25.Future<bool>.value(false),
          )
          as _i25.Future<bool>);
}

/// A class which mocks [SaveWatchlistMovie].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlistMovie extends _i1.Mock
    implements _i14.SaveWatchlistMovie {
  MockSaveWatchlistMovie() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.MovieRepository);

  @override
  _i25.Future<_i3.Either<_i23.Failure, String>> execute(
    _i2.MovieDetail? movie,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [movie]),
            returnValue: _i25.Future<_i3.Either<_i23.Failure, String>>.value(
              _FakeEither_2<_i23.Failure, String>(
                this,
                Invocation.method(#execute, [movie]),
              ),
            ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, String>>);
}

/// A class which mocks [RemoveWatchlistMovie].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlistMovie extends _i1.Mock
    implements _i15.RemoveWatchlistMovie {
  MockRemoveWatchlistMovie() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.MovieRepository);

  @override
  _i25.Future<_i3.Either<_i23.Failure, String>> execute(
    _i2.MovieDetail? movie,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [movie]),
            returnValue: _i25.Future<_i3.Either<_i23.Failure, String>>.value(
              _FakeEither_2<_i23.Failure, String>(
                this,
                Invocation.method(#execute, [movie]),
              ),
            ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, String>>);
}

/// A class which mocks [GetWatchlistMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistMovies extends _i1.Mock
    implements _i18.GetWatchlistMovies {
  MockGetWatchlistMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i25.Future<_i3.Either<_i23.Failure, List<_i2.Movie>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i25.Future<_i3.Either<_i23.Failure, List<_i2.Movie>>>.value(
                  _FakeEither_2<_i23.Failure, List<_i2.Movie>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, List<_i2.Movie>>>);
}

/// A class which mocks [GetWatchListTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchListTv extends _i1.Mock implements _i19.GetWatchListTv {
  MockGetWatchListTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>>.value(
                  _FakeEither_2<_i23.Failure, List<_i2.Tv>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>>);
}

/// A class which mocks [SearchMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchMovies extends _i1.Mock implements _i17.SearchMovies {
  MockSearchMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.MovieRepository);

  @override
  _i25.Future<_i3.Either<_i23.Failure, List<_i2.Movie>>> execute(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [query]),
            returnValue:
                _i25.Future<_i3.Either<_i23.Failure, List<_i2.Movie>>>.value(
                  _FakeEither_2<_i23.Failure, List<_i2.Movie>>(
                    this,
                    Invocation.method(#execute, [query]),
                  ),
                ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, List<_i2.Movie>>>);
}

/// A class which mocks [SearchTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchTv extends _i1.Mock implements _i16.SearchTv {
  MockSearchTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.TvRepository);

  @override
  _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>> execute(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [query]),
            returnValue:
                _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>>.value(
                  _FakeEither_2<_i23.Failure, List<_i2.Tv>>(
                    this,
                    Invocation.method(#execute, [query]),
                  ),
                ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>>);
}

/// A class which mocks [GetTvDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvDetail extends _i1.Mock implements _i6.GetTvDetail {
  MockGetTvDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.TvRepository);

  @override
  _i25.Future<_i3.Either<_i23.Failure, _i2.TvDetail>> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue:
                _i25.Future<_i3.Either<_i23.Failure, _i2.TvDetail>>.value(
                  _FakeEither_2<_i23.Failure, _i2.TvDetail>(
                    this,
                    Invocation.method(#execute, [id]),
                  ),
                ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, _i2.TvDetail>>);
}

/// A class which mocks [GetTvRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvRecommendations extends _i1.Mock
    implements _i7.GetTvRecommendations {
  MockGetTvRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.TvRepository);

  @override
  _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>> execute(dynamic id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue:
                _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>>.value(
                  _FakeEither_2<_i23.Failure, List<_i2.Tv>>(
                    this,
                    Invocation.method(#execute, [id]),
                  ),
                ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>>);
}

/// A class which mocks [GetWatchListStatusTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchListStatusTv extends _i1.Mock
    implements _i8.GetWatchListStatusTv {
  MockGetWatchListStatusTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.TvRepository);

  @override
  _i25.Future<bool> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue: _i25.Future<bool>.value(false),
          )
          as _i25.Future<bool>);
}

/// A class which mocks [SaveWatchlistTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlistTv extends _i1.Mock implements _i9.SaveWatchlistTv {
  MockSaveWatchlistTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.TvRepository);

  @override
  _i25.Future<_i3.Either<_i23.Failure, String>> execute(_i2.TvDetail? tv) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [tv]),
            returnValue: _i25.Future<_i3.Either<_i23.Failure, String>>.value(
              _FakeEither_2<_i23.Failure, String>(
                this,
                Invocation.method(#execute, [tv]),
              ),
            ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, String>>);
}

/// A class which mocks [RemoveWatchlistTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlistTv extends _i1.Mock implements _i10.RemoveWatchlistTv {
  MockRemoveWatchlistTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.TvRepository);

  @override
  _i25.Future<_i3.Either<_i23.Failure, String>> execute(_i2.TvDetail? tv) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [tv]),
            returnValue: _i25.Future<_i3.Either<_i23.Failure, String>>.value(
              _FakeEither_2<_i23.Failure, String>(
                this,
                Invocation.method(#execute, [tv]),
              ),
            ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, String>>);
}

/// A class which mocks [MovieDatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieDatabaseHelper extends _i1.Mock
    implements _i29.MovieDatabaseHelper {
  MockMovieDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i25.Future<_i30.Database?> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i25.Future<_i30.Database?>.value(),
          )
          as _i25.Future<_i30.Database?>);

  @override
  _i25.Future<void> insertCacheTransaction(
    List<_i2.MovieTable>? movies,
    String? category,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertCacheTransaction, [movies, category]),
            returnValue: _i25.Future<void>.value(),
            returnValueForMissingStub: _i25.Future<void>.value(),
          )
          as _i25.Future<void>);

  @override
  _i25.Future<List<Map<String, dynamic>>> getCacheMovies(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#getCacheMovies, [category]),
            returnValue: _i25.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i25.Future<List<Map<String, dynamic>>>);

  @override
  _i25.Future<int> clearCache(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, [category]),
            returnValue: _i25.Future<int>.value(0),
          )
          as _i25.Future<int>);

  @override
  _i25.Future<int> insertWatchlist(_i2.MovieTable? movie) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlist, [movie]),
            returnValue: _i25.Future<int>.value(0),
          )
          as _i25.Future<int>);

  @override
  _i25.Future<int> removeWatchlist(_i2.MovieTable? movie) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [movie]),
            returnValue: _i25.Future<int>.value(0),
          )
          as _i25.Future<int>);

  @override
  _i25.Future<Map<String, dynamic>?> getMovieById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieById, [id]),
            returnValue: _i25.Future<Map<String, dynamic>?>.value(),
          )
          as _i25.Future<Map<String, dynamic>?>);

  @override
  _i25.Future<List<Map<String, dynamic>>> getWatchlistMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistMovies, []),
            returnValue: _i25.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i25.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [TvDatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvDatabaseHelper extends _i1.Mock implements _i31.TvDatabaseHelper {
  MockTvDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i25.Future<_i30.Database?> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i25.Future<_i30.Database?>.value(),
          )
          as _i25.Future<_i30.Database?>);

  @override
  _i25.Future<void> insertCacheTransaction(
    List<_i2.TvTable>? tvs,
    String? category,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertCacheTransaction, [tvs, category]),
            returnValue: _i25.Future<void>.value(),
            returnValueForMissingStub: _i25.Future<void>.value(),
          )
          as _i25.Future<void>);

  @override
  _i25.Future<List<Map<String, dynamic>>> getCacheTvs(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#getCacheTvs, [category]),
            returnValue: _i25.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i25.Future<List<Map<String, dynamic>>>);

  @override
  _i25.Future<int> clearCache(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, [category]),
            returnValue: _i25.Future<int>.value(0),
          )
          as _i25.Future<int>);

  @override
  _i25.Future<int> insertWatchlist(_i2.TvTable? tv) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlist, [tv]),
            returnValue: _i25.Future<int>.value(0),
          )
          as _i25.Future<int>);

  @override
  _i25.Future<int> removeWatchlist(_i2.TvTable? tv) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [tv]),
            returnValue: _i25.Future<int>.value(0),
          )
          as _i25.Future<int>);

  @override
  _i25.Future<Map<String, dynamic>?> getTvById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvById, [id]),
            returnValue: _i25.Future<Map<String, dynamic>?>.value(),
          )
          as _i25.Future<Map<String, dynamic>?>);

  @override
  _i25.Future<List<Map<String, dynamic>>> getWatchlistTvs() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistTvs, []),
            returnValue: _i25.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i25.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [TopRatedTvNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopRatedTvNotifier extends _i1.Mock
    implements _i32.TopRatedTvNotifier {
  MockTopRatedTvNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTopRatedTv get getTopRatedTv =>
      (super.noSuchMethod(
            Invocation.getter(#getTopRatedTv),
            returnValue: _FakeGetTopRatedTv_6(
              this,
              Invocation.getter(#getTopRatedTv),
            ),
          )
          as _i2.GetTopRatedTv);

  @override
  _i23.RequestState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i23.RequestState.empty,
          )
          as _i23.RequestState);

  @override
  List<_i2.Tv> get tv =>
      (super.noSuchMethod(Invocation.getter(#tv), returnValue: <_i2.Tv>[])
          as List<_i2.Tv>);

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i24.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i25.Future<void> fetchTopRatedTv() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTopRatedTv, []),
            returnValue: _i25.Future<void>.value(),
            returnValueForMissingStub: _i25.Future<void>.value(),
          )
          as _i25.Future<void>);

  @override
  void addListener(_i26.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i26.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TvDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvDetailNotifier extends _i1.Mock implements _i33.TvDetailNotifier {
  MockTvDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.GetTvDetail get getTvDetail =>
      (super.noSuchMethod(
            Invocation.getter(#getTvDetail),
            returnValue: _FakeGetTvDetail_7(
              this,
              Invocation.getter(#getTvDetail),
            ),
          )
          as _i6.GetTvDetail);

  @override
  _i7.GetTvRecommendations get getTvRecommendations =>
      (super.noSuchMethod(
            Invocation.getter(#getTvRecommendations),
            returnValue: _FakeGetTvRecommendations_8(
              this,
              Invocation.getter(#getTvRecommendations),
            ),
          )
          as _i7.GetTvRecommendations);

  @override
  _i8.GetWatchListStatusTv get getWatchListStatus =>
      (super.noSuchMethod(
            Invocation.getter(#getWatchListStatus),
            returnValue: _FakeGetWatchListStatusTv_9(
              this,
              Invocation.getter(#getWatchListStatus),
            ),
          )
          as _i8.GetWatchListStatusTv);

  @override
  _i9.SaveWatchlistTv get saveWatchlist =>
      (super.noSuchMethod(
            Invocation.getter(#saveWatchlist),
            returnValue: _FakeSaveWatchlistTv_10(
              this,
              Invocation.getter(#saveWatchlist),
            ),
          )
          as _i9.SaveWatchlistTv);

  @override
  _i10.RemoveWatchlistTv get removeWatchlist =>
      (super.noSuchMethod(
            Invocation.getter(#removeWatchlist),
            returnValue: _FakeRemoveWatchlistTv_11(
              this,
              Invocation.getter(#removeWatchlist),
            ),
          )
          as _i10.RemoveWatchlistTv);

  @override
  _i23.RequestState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i23.RequestState.empty,
          )
          as _i23.RequestState);

  @override
  _i23.RequestState get recommendationState =>
      (super.noSuchMethod(
            Invocation.getter(#recommendationState),
            returnValue: _i23.RequestState.empty,
          )
          as _i23.RequestState);

  @override
  List<_i2.Tv> get tvRecommendations =>
      (super.noSuchMethod(
            Invocation.getter(#tvRecommendations),
            returnValue: <_i2.Tv>[],
          )
          as List<_i2.Tv>);

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i24.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
          )
          as String);

  @override
  bool get isAddedToWatchlist =>
      (super.noSuchMethod(
            Invocation.getter(#isAddedToWatchlist),
            returnValue: false,
          )
          as bool);

  @override
  String get watchlistMessage =>
      (super.noSuchMethod(
            Invocation.getter(#watchlistMessage),
            returnValue: _i24.dummyValue<String>(
              this,
              Invocation.getter(#watchlistMessage),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i25.Future<void> fetchTvDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTvDetail, [id]),
            returnValue: _i25.Future<void>.value(),
            returnValueForMissingStub: _i25.Future<void>.value(),
          )
          as _i25.Future<void>);

  @override
  _i25.Future<void> loadWatchlistStatus(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#loadWatchlistStatus, [id]),
            returnValue: _i25.Future<void>.value(),
            returnValueForMissingStub: _i25.Future<void>.value(),
          )
          as _i25.Future<void>);

  @override
  _i25.Future<void> addWatchlist(_i2.TvDetail? tv) =>
      (super.noSuchMethod(
            Invocation.method(#addWatchlist, [tv]),
            returnValue: _i25.Future<void>.value(),
            returnValueForMissingStub: _i25.Future<void>.value(),
          )
          as _i25.Future<void>);

  @override
  _i25.Future<void> removeFromWatchlist(_i2.TvDetail? tv) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromWatchlist, [tv]),
            returnValue: _i25.Future<void>.value(),
            returnValueForMissingStub: _i25.Future<void>.value(),
          )
          as _i25.Future<void>);

  @override
  void addListener(_i26.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i26.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PopularMoviesNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularMoviesNotifier extends _i1.Mock
    implements _i34.PopularMoviesNotifier {
  MockPopularMoviesNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetPopularMovies get getPopularMovies =>
      (super.noSuchMethod(
            Invocation.getter(#getPopularMovies),
            returnValue: _FakeGetPopularMovies_12(
              this,
              Invocation.getter(#getPopularMovies),
            ),
          )
          as _i2.GetPopularMovies);

  @override
  _i23.RequestState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i23.RequestState.empty,
          )
          as _i23.RequestState);

  @override
  List<_i2.Movie> get movies =>
      (super.noSuchMethod(
            Invocation.getter(#movies),
            returnValue: <_i2.Movie>[],
          )
          as List<_i2.Movie>);

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i24.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i25.Future<void> fetchPopularMovies() =>
      (super.noSuchMethod(
            Invocation.method(#fetchPopularMovies, []),
            returnValue: _i25.Future<void>.value(),
            returnValueForMissingStub: _i25.Future<void>.value(),
          )
          as _i25.Future<void>);

  @override
  void addListener(_i26.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i26.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [MovieDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieDetailNotifier extends _i1.Mock
    implements _i35.MovieDetailNotifier {
  MockMovieDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.GetMovieDetail get getMovieDetail =>
      (super.noSuchMethod(
            Invocation.getter(#getMovieDetail),
            returnValue: _FakeGetMovieDetail_13(
              this,
              Invocation.getter(#getMovieDetail),
            ),
          )
          as _i11.GetMovieDetail);

  @override
  _i12.GetMovieRecommendations get getMovieRecommendations =>
      (super.noSuchMethod(
            Invocation.getter(#getMovieRecommendations),
            returnValue: _FakeGetMovieRecommendations_14(
              this,
              Invocation.getter(#getMovieRecommendations),
            ),
          )
          as _i12.GetMovieRecommendations);

  @override
  _i13.GetWatchListStatusMovie get getWatchListStatus =>
      (super.noSuchMethod(
            Invocation.getter(#getWatchListStatus),
            returnValue: _FakeGetWatchListStatusMovie_15(
              this,
              Invocation.getter(#getWatchListStatus),
            ),
          )
          as _i13.GetWatchListStatusMovie);

  @override
  _i14.SaveWatchlistMovie get saveWatchlist =>
      (super.noSuchMethod(
            Invocation.getter(#saveWatchlist),
            returnValue: _FakeSaveWatchlistMovie_16(
              this,
              Invocation.getter(#saveWatchlist),
            ),
          )
          as _i14.SaveWatchlistMovie);

  @override
  _i15.RemoveWatchlistMovie get removeWatchlist =>
      (super.noSuchMethod(
            Invocation.getter(#removeWatchlist),
            returnValue: _FakeRemoveWatchlistMovie_17(
              this,
              Invocation.getter(#removeWatchlist),
            ),
          )
          as _i15.RemoveWatchlistMovie);

  @override
  _i2.MovieDetail get movie =>
      (super.noSuchMethod(
            Invocation.getter(#movie),
            returnValue: _FakeMovieDetail_18(this, Invocation.getter(#movie)),
          )
          as _i2.MovieDetail);

  @override
  _i23.RequestState get movieState =>
      (super.noSuchMethod(
            Invocation.getter(#movieState),
            returnValue: _i23.RequestState.empty,
          )
          as _i23.RequestState);

  @override
  List<_i2.Movie> get movieRecommendations =>
      (super.noSuchMethod(
            Invocation.getter(#movieRecommendations),
            returnValue: <_i2.Movie>[],
          )
          as List<_i2.Movie>);

  @override
  _i23.RequestState get recommendationState =>
      (super.noSuchMethod(
            Invocation.getter(#recommendationState),
            returnValue: _i23.RequestState.empty,
          )
          as _i23.RequestState);

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i24.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
          )
          as String);

  @override
  bool get isAddedToWatchlist =>
      (super.noSuchMethod(
            Invocation.getter(#isAddedToWatchlist),
            returnValue: false,
          )
          as bool);

  @override
  String get watchlistMessage =>
      (super.noSuchMethod(
            Invocation.getter(#watchlistMessage),
            returnValue: _i24.dummyValue<String>(
              this,
              Invocation.getter(#watchlistMessage),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i25.Future<void> fetchMovieDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchMovieDetail, [id]),
            returnValue: _i25.Future<void>.value(),
            returnValueForMissingStub: _i25.Future<void>.value(),
          )
          as _i25.Future<void>);

  @override
  _i25.Future<void> addWatchlist(_i2.MovieDetail? movie) =>
      (super.noSuchMethod(
            Invocation.method(#addWatchlist, [movie]),
            returnValue: _i25.Future<void>.value(),
            returnValueForMissingStub: _i25.Future<void>.value(),
          )
          as _i25.Future<void>);

  @override
  _i25.Future<void> removeFromWatchlist(_i2.MovieDetail? movie) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromWatchlist, [movie]),
            returnValue: _i25.Future<void>.value(),
            returnValueForMissingStub: _i25.Future<void>.value(),
          )
          as _i25.Future<void>);

  @override
  _i25.Future<void> loadWatchlistStatus(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#loadWatchlistStatus, [id]),
            returnValue: _i25.Future<void>.value(),
            returnValueForMissingStub: _i25.Future<void>.value(),
          )
          as _i25.Future<void>);

  @override
  void addListener(_i26.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i26.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PopularTvNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularTvNotifier extends _i1.Mock implements _i36.PopularTvNotifier {
  MockPopularTvNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetPopularTv get getPopularTv =>
      (super.noSuchMethod(
            Invocation.getter(#getPopularTv),
            returnValue: _FakeGetPopularTv_19(
              this,
              Invocation.getter(#getPopularTv),
            ),
          )
          as _i2.GetPopularTv);

  @override
  _i23.RequestState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i23.RequestState.empty,
          )
          as _i23.RequestState);

  @override
  List<_i2.Tv> get tv =>
      (super.noSuchMethod(Invocation.getter(#tv), returnValue: <_i2.Tv>[])
          as List<_i2.Tv>);

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i24.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i25.Future<void> fetchPopularTv() =>
      (super.noSuchMethod(
            Invocation.method(#fetchPopularTv, []),
            returnValue: _i25.Future<void>.value(),
            returnValueForMissingStub: _i25.Future<void>.value(),
          )
          as _i25.Future<void>);

  @override
  void addListener(_i26.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i26.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GetPopularTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPopularTv extends _i1.Mock implements _i2.GetPopularTv {
  MockGetPopularTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.TvRepository);

  @override
  _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>>.value(
                  _FakeEither_2<_i23.Failure, List<_i2.Tv>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i25.Future<_i3.Either<_i23.Failure, List<_i2.Tv>>>);
}

/// A class which mocks [TvSearchNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSearchNotifier extends _i1.Mock implements _i37.TvSearchNotifier {
  MockTvSearchNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.SearchTv get searchTv =>
      (super.noSuchMethod(
            Invocation.getter(#searchTv),
            returnValue: _FakeSearchTv_20(this, Invocation.getter(#searchTv)),
          )
          as _i16.SearchTv);

  @override
  _i23.RequestState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i23.RequestState.empty,
          )
          as _i23.RequestState);

  @override
  List<_i2.Tv> get searchResult =>
      (super.noSuchMethod(
            Invocation.getter(#searchResult),
            returnValue: <_i2.Tv>[],
          )
          as List<_i2.Tv>);

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i24.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i25.Future<void> fetchTvSearch(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTvSearch, [query]),
            returnValue: _i25.Future<void>.value(),
            returnValueForMissingStub: _i25.Future<void>.value(),
          )
          as _i25.Future<void>);

  @override
  void addListener(_i26.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i26.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [MovieSearchNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieSearchNotifier extends _i1.Mock
    implements _i38.MovieSearchNotifier {
  MockMovieSearchNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i17.SearchMovies get searchMovies =>
      (super.noSuchMethod(
            Invocation.getter(#searchMovies),
            returnValue: _FakeSearchMovies_21(
              this,
              Invocation.getter(#searchMovies),
            ),
          )
          as _i17.SearchMovies);

  @override
  _i23.RequestState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i23.RequestState.empty,
          )
          as _i23.RequestState);

  @override
  List<_i2.Movie> get searchResult =>
      (super.noSuchMethod(
            Invocation.getter(#searchResult),
            returnValue: <_i2.Movie>[],
          )
          as List<_i2.Movie>);

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i24.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i25.Future<void> fetchMovieSearch(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#fetchMovieSearch, [query]),
            returnValue: _i25.Future<void>.value(),
            returnValueForMissingStub: _i25.Future<void>.value(),
          )
          as _i25.Future<void>);

  @override
  void addListener(_i26.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i26.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [WatchlistMovieNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistMovieNotifier extends _i1.Mock
    implements _i39.WatchlistMovieNotifier {
  MockWatchlistMovieNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.GetWatchlistMovies get getWatchlistMovies =>
      (super.noSuchMethod(
            Invocation.getter(#getWatchlistMovies),
            returnValue: _FakeGetWatchlistMovies_22(
              this,
              Invocation.getter(#getWatchlistMovies),
            ),
          )
          as _i18.GetWatchlistMovies);

  @override
  List<_i2.Movie> get watchlistMovies =>
      (super.noSuchMethod(
            Invocation.getter(#watchlistMovies),
            returnValue: <_i2.Movie>[],
          )
          as List<_i2.Movie>);

  @override
  _i23.RequestState get watchlistState =>
      (super.noSuchMethod(
            Invocation.getter(#watchlistState),
            returnValue: _i23.RequestState.empty,
          )
          as _i23.RequestState);

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i24.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i25.Future<void> fetchWatchlistMovies() =>
      (super.noSuchMethod(
            Invocation.method(#fetchWatchlistMovies, []),
            returnValue: _i25.Future<void>.value(),
            returnValueForMissingStub: _i25.Future<void>.value(),
          )
          as _i25.Future<void>);

  @override
  void addListener(_i26.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i26.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [WatchlistTvNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistTvNotifier extends _i1.Mock
    implements _i40.WatchlistTvNotifier {
  MockWatchlistTvNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.GetWatchListTv get getWatchlistTv =>
      (super.noSuchMethod(
            Invocation.getter(#getWatchlistTv),
            returnValue: _FakeGetWatchListTv_23(
              this,
              Invocation.getter(#getWatchlistTv),
            ),
          )
          as _i19.GetWatchListTv);

  @override
  List<_i2.Tv> get watchlistTv =>
      (super.noSuchMethod(
            Invocation.getter(#watchlistTv),
            returnValue: <_i2.Tv>[],
          )
          as List<_i2.Tv>);

  @override
  _i23.RequestState get watchlistState =>
      (super.noSuchMethod(
            Invocation.getter(#watchlistState),
            returnValue: _i23.RequestState.empty,
          )
          as _i23.RequestState);

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i24.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i25.Future<void> fetchWatchlistTv() =>
      (super.noSuchMethod(
            Invocation.method(#fetchWatchlistTv, []),
            returnValue: _i25.Future<void>.value(),
            returnValueForMissingStub: _i25.Future<void>.value(),
          )
          as _i25.Future<void>);

  @override
  void addListener(_i26.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i26.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DataConnectionChecker].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataConnectionChecker extends _i1.Mock
    implements _i20.DataConnectionChecker {
  MockDataConnectionChecker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i20.AddressCheckOptions> get addresses =>
      (super.noSuchMethod(
            Invocation.getter(#addresses),
            returnValue: <_i20.AddressCheckOptions>[],
          )
          as List<_i20.AddressCheckOptions>);

  @override
  Duration get checkInterval =>
      (super.noSuchMethod(
            Invocation.getter(#checkInterval),
            returnValue: _FakeDuration_24(
              this,
              Invocation.getter(#checkInterval),
            ),
          )
          as Duration);

  @override
  List<_i20.AddressCheckResult> get lastTryResults =>
      (super.noSuchMethod(
            Invocation.getter(#lastTryResults),
            returnValue: <_i20.AddressCheckResult>[],
          )
          as List<_i20.AddressCheckResult>);

  @override
  _i25.Future<bool> get hasConnection =>
      (super.noSuchMethod(
            Invocation.getter(#hasConnection),
            returnValue: _i25.Future<bool>.value(false),
          )
          as _i25.Future<bool>);

  @override
  _i25.Future<_i20.DataConnectionStatus> get connectionStatus =>
      (super.noSuchMethod(
            Invocation.getter(#connectionStatus),
            returnValue: _i25.Future<_i20.DataConnectionStatus>.value(
              _i20.DataConnectionStatus.disconnected,
            ),
          )
          as _i25.Future<_i20.DataConnectionStatus>);

  @override
  _i25.Stream<_i20.DataConnectionStatus> get onStatusChange =>
      (super.noSuchMethod(
            Invocation.getter(#onStatusChange),
            returnValue: _i25.Stream<_i20.DataConnectionStatus>.empty(),
          )
          as _i25.Stream<_i20.DataConnectionStatus>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  bool get isActivelyChecking =>
      (super.noSuchMethod(
            Invocation.getter(#isActivelyChecking),
            returnValue: false,
          )
          as bool);

  @override
  set addresses(List<_i20.AddressCheckOptions>? _addresses) =>
      super.noSuchMethod(
        Invocation.setter(#addresses, _addresses),
        returnValueForMissingStub: null,
      );

  @override
  set checkInterval(Duration? _checkInterval) => super.noSuchMethod(
    Invocation.setter(#checkInterval, _checkInterval),
    returnValueForMissingStub: null,
  );

  @override
  _i25.Future<_i20.AddressCheckResult> isHostReachable(
    _i20.AddressCheckOptions? options,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isHostReachable, [options]),
            returnValue: _i25.Future<_i20.AddressCheckResult>.value(
              _FakeAddressCheckResult_25(
                this,
                Invocation.method(#isHostReachable, [options]),
              ),
            ),
          )
          as _i25.Future<_i20.AddressCheckResult>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i21.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i25.Future<_i21.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#head, [url], {#headers: headers}),
            returnValue: _i25.Future<_i21.Response>.value(
              _FakeResponse_26(
                this,
                Invocation.method(#head, [url], {#headers: headers}),
              ),
            ),
          )
          as _i25.Future<_i21.Response>);

  @override
  _i25.Future<_i21.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [url], {#headers: headers}),
            returnValue: _i25.Future<_i21.Response>.value(
              _FakeResponse_26(
                this,
                Invocation.method(#get, [url], {#headers: headers}),
              ),
            ),
          )
          as _i25.Future<_i21.Response>);

  @override
  _i25.Future<_i21.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i41.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i25.Future<_i21.Response>.value(
              _FakeResponse_26(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i25.Future<_i21.Response>);

  @override
  _i25.Future<_i21.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i41.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i25.Future<_i21.Response>.value(
              _FakeResponse_26(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i25.Future<_i21.Response>);

  @override
  _i25.Future<_i21.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i41.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i25.Future<_i21.Response>.value(
              _FakeResponse_26(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i25.Future<_i21.Response>);

  @override
  _i25.Future<_i21.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i41.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i25.Future<_i21.Response>.value(
              _FakeResponse_26(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i25.Future<_i21.Response>);

  @override
  _i25.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [url], {#headers: headers}),
            returnValue: _i25.Future<String>.value(
              _i24.dummyValue<String>(
                this,
                Invocation.method(#read, [url], {#headers: headers}),
              ),
            ),
          )
          as _i25.Future<String>);

  @override
  _i25.Future<_i42.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readBytes, [url], {#headers: headers}),
            returnValue: _i25.Future<_i42.Uint8List>.value(_i42.Uint8List(0)),
          )
          as _i25.Future<_i42.Uint8List>);

  @override
  _i25.Future<_i21.StreamedResponse> send(_i21.BaseRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue: _i25.Future<_i21.StreamedResponse>.value(
              _FakeStreamedResponse_27(
                this,
                Invocation.method(#send, [request]),
              ),
            ),
          )
          as _i25.Future<_i21.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSourceImpl extends _i1.Mock
    implements _i27.MovieRemoteDataSource {
  MockMovieRemoteDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i25.Future<List<_i2.MovieModel>> getNowPlayingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlayingMovies, []),
            returnValue: _i25.Future<List<_i2.MovieModel>>.value(
              <_i2.MovieModel>[],
            ),
          )
          as _i25.Future<List<_i2.MovieModel>>);

  @override
  _i25.Future<List<_i2.MovieModel>> getPopularMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularMovies, []),
            returnValue: _i25.Future<List<_i2.MovieModel>>.value(
              <_i2.MovieModel>[],
            ),
          )
          as _i25.Future<List<_i2.MovieModel>>);

  @override
  _i25.Future<List<_i2.MovieModel>> getTopRatedMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedMovies, []),
            returnValue: _i25.Future<List<_i2.MovieModel>>.value(
              <_i2.MovieModel>[],
            ),
          )
          as _i25.Future<List<_i2.MovieModel>>);

  @override
  _i25.Future<_i4.MovieDetailResponse> getMovieDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieDetail, [id]),
            returnValue: _i25.Future<_i4.MovieDetailResponse>.value(
              _FakeMovieDetailResponse_4(
                this,
                Invocation.method(#getMovieDetail, [id]),
              ),
            ),
          )
          as _i25.Future<_i4.MovieDetailResponse>);

  @override
  _i25.Future<List<_i2.MovieModel>> getMovieRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieRecommendations, [id]),
            returnValue: _i25.Future<List<_i2.MovieModel>>.value(
              <_i2.MovieModel>[],
            ),
          )
          as _i25.Future<List<_i2.MovieModel>>);

  @override
  _i25.Future<List<_i2.MovieModel>> searchMovies(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchMovies, [query]),
            returnValue: _i25.Future<List<_i2.MovieModel>>.value(
              <_i2.MovieModel>[],
            ),
          )
          as _i25.Future<List<_i2.MovieModel>>);
}

/// A class which mocks [TvRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRemoteDataSourceImpl extends _i1.Mock
    implements _i28.TvRemoteDataSource {
  MockTvRemoteDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i25.Future<List<_i2.TvModel>> getOnTheAirTv() =>
      (super.noSuchMethod(
            Invocation.method(#getOnTheAirTv, []),
            returnValue: _i25.Future<List<_i2.TvModel>>.value(<_i2.TvModel>[]),
          )
          as _i25.Future<List<_i2.TvModel>>);

  @override
  _i25.Future<List<_i2.TvModel>> getPopularTv() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTv, []),
            returnValue: _i25.Future<List<_i2.TvModel>>.value(<_i2.TvModel>[]),
          )
          as _i25.Future<List<_i2.TvModel>>);

  @override
  _i25.Future<List<_i2.TvModel>> getTopRatedTv() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedTv, []),
            returnValue: _i25.Future<List<_i2.TvModel>>.value(<_i2.TvModel>[]),
          )
          as _i25.Future<List<_i2.TvModel>>);

  @override
  _i25.Future<_i5.TvDetailResponse> getTvDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvDetail, [id]),
            returnValue: _i25.Future<_i5.TvDetailResponse>.value(
              _FakeTvDetailResponse_5(
                this,
                Invocation.method(#getTvDetail, [id]),
              ),
            ),
          )
          as _i25.Future<_i5.TvDetailResponse>);

  @override
  _i25.Future<List<_i2.TvModel>> searchTv(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTv, [query]),
            returnValue: _i25.Future<List<_i2.TvModel>>.value(<_i2.TvModel>[]),
          )
          as _i25.Future<List<_i2.TvModel>>);

  @override
  _i25.Future<List<_i2.TvModel>> getTvRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvRecommendations, [id]),
            returnValue: _i25.Future<List<_i2.TvModel>>.value(<_i2.TvModel>[]),
          )
          as _i25.Future<List<_i2.TvModel>>);
}

/// A class which mocks [MovieLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieLocalDataSource extends _i1.Mock
    implements _i43.MovieLocalDataSource {
  MockMovieLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i25.Future<void> cacheNowPlayingMovies(List<_i2.MovieTable>? movies) =>
      (super.noSuchMethod(
            Invocation.method(#cacheNowPlayingMovies, [movies]),
            returnValue: _i25.Future<void>.value(),
            returnValueForMissingStub: _i25.Future<void>.value(),
          )
          as _i25.Future<void>);

  @override
  _i25.Future<List<_i2.MovieTable>> getCachedNowPlayingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedNowPlayingMovies, []),
            returnValue: _i25.Future<List<_i2.MovieTable>>.value(
              <_i2.MovieTable>[],
            ),
          )
          as _i25.Future<List<_i2.MovieTable>>);

  @override
  _i25.Future<String> insertWatchlist(_i2.MovieTable? movie) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlist, [movie]),
            returnValue: _i25.Future<String>.value(
              _i24.dummyValue<String>(
                this,
                Invocation.method(#insertWatchlist, [movie]),
              ),
            ),
          )
          as _i25.Future<String>);

  @override
  _i25.Future<String> removeWatchlist(_i2.MovieTable? movie) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [movie]),
            returnValue: _i25.Future<String>.value(
              _i24.dummyValue<String>(
                this,
                Invocation.method(#removeWatchlist, [movie]),
              ),
            ),
          )
          as _i25.Future<String>);

  @override
  _i25.Future<_i2.MovieTable?> getMovieById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieById, [id]),
            returnValue: _i25.Future<_i2.MovieTable?>.value(),
          )
          as _i25.Future<_i2.MovieTable?>);

  @override
  _i25.Future<List<_i2.MovieTable>> getWatchlistMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistMovies, []),
            returnValue: _i25.Future<List<_i2.MovieTable>>.value(
              <_i2.MovieTable>[],
            ),
          )
          as _i25.Future<List<_i2.MovieTable>>);
}

/// A class which mocks [TvLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvLocalDataSource extends _i1.Mock implements _i44.TvLocalDataSource {
  MockTvLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i25.Future<void> cacheOnTheAirTv(List<_i2.TvTable>? tvs) =>
      (super.noSuchMethod(
            Invocation.method(#cacheOnTheAirTv, [tvs]),
            returnValue: _i25.Future<void>.value(),
            returnValueForMissingStub: _i25.Future<void>.value(),
          )
          as _i25.Future<void>);

  @override
  _i25.Future<List<_i2.TvTable>> getCachedOnTheAirTv() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedOnTheAirTv, []),
            returnValue: _i25.Future<List<_i2.TvTable>>.value(<_i2.TvTable>[]),
          )
          as _i25.Future<List<_i2.TvTable>>);

  @override
  _i25.Future<String> insertWatchlist(_i2.TvTable? tv) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlist, [tv]),
            returnValue: _i25.Future<String>.value(
              _i24.dummyValue<String>(
                this,
                Invocation.method(#insertWatchlist, [tv]),
              ),
            ),
          )
          as _i25.Future<String>);

  @override
  _i25.Future<String> removeWatchlist(_i2.TvTable? tv) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [tv]),
            returnValue: _i25.Future<String>.value(
              _i24.dummyValue<String>(
                this,
                Invocation.method(#removeWatchlist, [tv]),
              ),
            ),
          )
          as _i25.Future<String>);

  @override
  _i25.Future<_i2.TvTable?> getTvById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvById, [id]),
            returnValue: _i25.Future<_i2.TvTable?>.value(),
          )
          as _i25.Future<_i2.TvTable?>);

  @override
  _i25.Future<List<_i2.TvTable>> getWatchlistTvs() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistTvs, []),
            returnValue: _i25.Future<List<_i2.TvTable>>.value(<_i2.TvTable>[]),
          )
          as _i25.Future<List<_i2.TvTable>>);
}
